[package]
name = "common"
version = "0.1.0"
authors = ["Michal HornickÃ½ <semtexzv@gmail.com>"]

[dependencies]
gl = "*"
glium = { version = "*", no-default-features = true }
error-chain = "*"
reqwest = "*"

serde="*"
serde_derive="*"
serde_json="*"


palette = "0.4"
